// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {usage} from '../models';
import {config} from '../models';
import {provider} from '../models';

export function CompleteGrokDeviceAuth(arg1:string,arg2:string):Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function GetChannels():Promise<Array<service.ChannelView>>;

export function GetPresets():Promise<Array<service.PresetView>>;

export function GetSettings():Promise<service.SettingsView>;

export function GetUsageSummary(arg1:string):Promise<Array<usage.AggRow>>;

export function SaveChannel(arg1:config.Channel):Promise<void>;

export function SaveSettings(arg1:service.SettingsView):Promise<void>;

export function StartGrokDeviceAuth(arg1:string):Promise<provider.DeviceAuthInfo>;

export function TestChannel(arg1:string):Promise<void>;
