// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {provider} from '../models';
import {usage} from '../models';
import {config} from '../models';

export function CompleteGrokDeviceAuth(arg1:string,arg2:string):Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ExportProviders():Promise<string>;

export function GetChannels():Promise<Array<service.ChannelView>>;

export function GetPresets():Promise<Array<service.PresetView>>;

export function GetProviderBalance(arg1:string):Promise<service.BalanceView>;

export function GetProviderKeys(arg1:string):Promise<service.ProviderKeysView>;

export function GetProviderModels(arg1:string):Promise<Array<provider.ModelInfo>>;

export function GetProviderUsage(arg1:string):Promise<service.ProviderUsageView>;

export function GetProviders():Promise<Array<service.ProviderView>>;

export function GetSettings():Promise<service.SettingsView>;

export function GetUsageDaily(arg1:string):Promise<Array<usage.ModelDayTokens>>;

export function GetUsageSummary(arg1:string):Promise<Array<usage.AggRow>>;

export function ImportProviders():Promise<string>;

export function ReorderProviders(arg1:Array<string>):Promise<void>;

export function SaveChannel(arg1:config.Channel,arg2:string):Promise<void>;

export function SaveProvider(arg1:config.ProviderAccount):Promise<void>;

export function SaveSettings(arg1:service.SettingsView):Promise<void>;

export function StartGrokDeviceAuth(arg1:string):Promise<provider.DeviceAuthInfo>;

export function TestChannel(arg1:string):Promise<void>;

export function TestProvider(arg1:string):Promise<void>;
