// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteGrokDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['CompleteGrokDeviceAuth'](arg1, arg2);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUsageSummary(arg1) {
  return window['go']['main']['App']['GetUsageSummary'](arg1);
}

export function SaveChannel(arg1) {
  return window['go']['main']['App']['SaveChannel'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartGrokDeviceAuth(arg1) {
  return window['go']['main']['App']['StartGrokDeviceAuth'](arg1);
}

export function TestChannel(arg1) {
  return window['go']['main']['App']['TestChannel'](arg1);
}
