// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteGrokDeviceAuth(arg1, arg2) {
  return window['go']['main']['App']['CompleteGrokDeviceAuth'](arg1, arg2);
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function ExportProviders() {
  return window['go']['main']['App']['ExportProviders']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetPresets() {
  return window['go']['main']['App']['GetPresets']();
}

export function GetProviderBalance(arg1) {
  return window['go']['main']['App']['GetProviderBalance'](arg1);
}

export function GetProviderKeys(arg1) {
  return window['go']['main']['App']['GetProviderKeys'](arg1);
}

export function GetProviderModels(arg1) {
  return window['go']['main']['App']['GetProviderModels'](arg1);
}

export function GetProviderUsage(arg1) {
  return window['go']['main']['App']['GetProviderUsage'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUsageDaily(arg1) {
  return window['go']['main']['App']['GetUsageDaily'](arg1);
}

export function GetUsageHourlyToday() {
  return window['go']['main']['App']['GetUsageHourlyToday']();
}

export function GetUsageSummary(arg1) {
  return window['go']['main']['App']['GetUsageSummary'](arg1);
}

export function ImportProviders() {
  return window['go']['main']['App']['ImportProviders']();
}

export function ReorderProviders(arg1) {
  return window['go']['main']['App']['ReorderProviders'](arg1);
}

export function SaveChannel(arg1, arg2) {
  return window['go']['main']['App']['SaveChannel'](arg1, arg2);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartGrokDeviceAuth(arg1) {
  return window['go']['main']['App']['StartGrokDeviceAuth'](arg1);
}

export function TestChannel(arg1) {
  return window['go']['main']['App']['TestChannel'](arg1);
}

export function TestProvider(arg1) {
  return window['go']['main']['App']['TestProvider'](arg1);
}
